language: rust
rust:
  - stable
    env: SERVER_PORT_RANGE_START=7000
  - beta
    env: SERVER_PORT_RANGE_START=8000
  - nightly
    env: SERVER_PORT_RANGE_START=9000
matrix:
  allow_failures:
    - rust: nightly
