language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - rust: stable
      env: SERVER_PORT_RANGE_START=7000
    - rust: beta
      env: SERVER_PORT_RANGE_START=8000
    - rust: nightly
      env: SERVER_PORT_RANGE_START=9000
  allow_failures:
    - rust: nightly
