[package]
name = "osmium_example_http2_file_server"
version = "0.1.0"
authors = ["ThetaSinner <greatdjonfire@hotmail.co.uk>"]

[dependencies]
log = "0.3"
pretty_env_logger = "0.1.1"

[dependencies.osmium]
path = "../../../"
default-features = false
features = ["osmium_support"]
