[package]
name = "osmium_example_http_file_server"
version = "0.1.0"
authors = ["ThetaSinner <greatdjonfire@hotmail.co.uk>"]

[dependencies]
osmium = { path = "../../../" }
log = "0.3"
pretty_env_logger = "0.1.1"
